name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    strategy:
      matrix:
        project:
          - user-table
          - todo-list

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies and build ${{ matrix.project }}
        run: |
          cd tasks/${{ matrix.project }}
          npm install
          npm run build

      - name: Configure git
        run: |
          git config --global user.email "m.gladyshew@yandex.ru"
          git config --global user.name "schenok"
          git config --global url.https://${{ secrets.MY_PAT }}@github.com/.insteadOf https://github.com/

      - name: Deploy ${{ matrix.project }} to GitHub Pages
        run: |
          cd tasks/${{ matrix.project }}
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
